### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
null_V=np.zeros(10,dtype=int)

In [2]:
null_V[4]=1

In [3]:
print(null_V)

[0 0 0 0 1 0 0 0 0 0]


### 2. Create a vector with values ranging from 10 to 49.

In [4]:
array=np.arange(10,50)

In [5]:
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3.Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
array1=np.arange(0,9).reshape(3,3)

In [7]:
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [8]:
array=np.array([1,2,0,0,4,0])
new_array=np.nonzero(array==0)

In [9]:
print(new_array)

(array([2, 3, 5], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
ran_array=np.random.random((10,10))

In [11]:
print(ran_array)

[[0.85012163 0.56611966 0.18011289 0.11453853 0.06054486 0.33446816
  0.72148327 0.90443749 0.62186546 0.99737107]
 [0.83409383 0.16381839 0.64060531 0.26223063 0.39157314 0.2343782
  0.99070498 0.1920988  0.8747055  0.22309089]
 [0.76121061 0.88458781 0.68054948 0.12869111 0.0718468  0.96814461
  0.58756742 0.1117463  0.09575791 0.95953647]
 [0.93960302 0.78860846 0.34268644 0.76351927 0.33313151 0.48049775
  0.79490318 0.99749727 0.11397305 0.71461672]
 [0.99896591 0.1889019  0.50041424 0.71194187 0.12614608 0.62365289
  0.65369518 0.4319991  0.67338515 0.1505793 ]
 [0.531669   0.43750143 0.89940308 0.55090166 0.55634109 0.87471423
  0.46744689 0.61772755 0.07999879 0.41519118]
 [0.432842   0.90455447 0.95244208 0.62683455 0.84284469 0.10293042
  0.27676492 0.23929914 0.65918737 0.13506643]
 [0.12186857 0.58620357 0.75162015 0.17225044 0.04817425 0.36482539
  0.98106505 0.97873787 0.53104372 0.23107163]
 [0.36435434 0.67248104 0.5012292  0.79106969 0.99828411 0.35438538
  0.49961035 

In [12]:
print("Minimun Value :",ran_array.min())

Minimun Value : 0.04817424715419438


In [13]:
print("Maximum Value :",ran_array.max())

Maximum Value : 0.9989659062722529


### 6. Create a random vector of size 30 and find the mean value.

In [19]:
ran_aaray=np.random.random(30)

In [18]:
print(ran_array)

[[0.85012163 0.56611966 0.18011289 0.11453853 0.06054486 0.33446816
  0.72148327 0.90443749 0.62186546 0.99737107]
 [0.83409383 0.16381839 0.64060531 0.26223063 0.39157314 0.2343782
  0.99070498 0.1920988  0.8747055  0.22309089]
 [0.76121061 0.88458781 0.68054948 0.12869111 0.0718468  0.96814461
  0.58756742 0.1117463  0.09575791 0.95953647]
 [0.93960302 0.78860846 0.34268644 0.76351927 0.33313151 0.48049775
  0.79490318 0.99749727 0.11397305 0.71461672]
 [0.99896591 0.1889019  0.50041424 0.71194187 0.12614608 0.62365289
  0.65369518 0.4319991  0.67338515 0.1505793 ]
 [0.531669   0.43750143 0.89940308 0.55090166 0.55634109 0.87471423
  0.46744689 0.61772755 0.07999879 0.41519118]
 [0.432842   0.90455447 0.95244208 0.62683455 0.84284469 0.10293042
  0.27676492 0.23929914 0.65918737 0.13506643]
 [0.12186857 0.58620357 0.75162015 0.17225044 0.04817425 0.36482539
  0.98106505 0.97873787 0.53104372 0.23107163]
 [0.36435434 0.67248104 0.5012292  0.79106969 0.99828411 0.35438538
  0.49961035 

In [21]:
print("Mean :",ran_array.mean())

Mean : 0.5424203826195341
